# Site settings
title: Code & Security
header-img: img/home-bg.jpg
email: frederik.ingwersen@gmail.com
copyright_name: This does not have rights
description: "Blog & resumé of Frederik Ingwersen"
baseurl: ""
url: "http://fredingwersen.com"
twitter_username: Fred_Ingwersen
github_username:  FredIngwersen
email_username:  frederik.ingwersen@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
